### ISSUE TITLE
Door handle seperates from door

### ISSUE THREAD

**Issue by ottedam** [vr4vet/cloud-engineering#14]
The white door handle block can get seperated from the actual door. This might happen when something (for instance the body of the player) is blocking the door but not the handle

**Comment by AndreasAch** [comment]
I am having trouble re-creating this bug to see what is causing it. Any particular cabinet that does this consistently?

**Comment by ottedam** [comment]
Only had this once, when someone else was playing. Not sure which cabinet it was but there should be no difference as they are all the same prefab.

**Comment by ottedam** [comment]
Unable to recreate so lets close for now
