### ISSUE TITLE
Fix physical interaction

### ISSUE THREAD

**Issue by ottedam** [vr4vet/cloud-engineering#6]

**Comment by ingolvjr** [comment]
@ottedam does this include the ram stick only interacting with the table they are spawned on?

**Comment by ottedam** [comment]
> @ottedam does this include the ram stick only interacting with the table they are spawned on?

Do you mean the ram stick falling through the floor? This was actually a byproduct of the fix for this issue. This issue was meant for the player being able to take flight. I made a mistake where I made the floor part of the player which caused the RAM to fall through the floor. I just pushed this fix to our main.

@ingolvjr

**Comment by ingolvjr** [comment]
ah, then I see
